name: Build LLVM for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # 使用Windows虚拟环境
    env:
      BUILD_PROJECT: clang
      BUILD_MASTER: false

    # strategy:
      # fail-fast: false
      # matrix:
        # CRT:
          # -  msvcrt
          # -  libcmt
  
        # TARGET_CPU:
        # -  x86
        # -  amd64
  
        # CONFIGURATION:
        # -   Debug
        # -   Release

    steps:
    - name: Checkout Self
      uses: actions/checkout@v2
  
    # - name: Install CMake
    #   uses: lukka/get-cmake@v3.27.4
      with:
        cmake-version: '3.25'  # 指定需要的CMake版本

    # - name: Setup MSBuild
      # uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '17.3'  # 指定需要的Visual Studio版本
        msbuild-architecture: x64

    - name: Set up LLVM source and build directories
      run: |
        mkdir llvm-source
        mkdir llvm-build
        git clone https://github.com/llvm/llvm-project.git --single-branch --branch release/17.x llvm-source
        cd llvm-build
        cmake -G "Visual Studio 17.3 2022" -A x64 ../llvm-source/llvm
      working-directory: ${{ github.workspace }}

    - name: Build LLVM
      run: |
        cmake --build . --config Release
      working-directory: ${{ github.workspace }}/llvm-build
