# This is a basic workflow to help you get started with Actions

name: toy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      BUILD_PROJECT: clang
      BUILD_MASTER: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # - name: Test Msbuild
      #   uses: microsoft/setup-msbuild@v1.1

      - name: zip 
        shell: powershell
        run: | 
          echo 111 > 2.txt
          Compress-Archive -LiteralPath .\ -DestinationPath r.zip
        
      - name: Test Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        # env: 
        #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: rel-t # ${{ github.ref }}
          name: Release ${{ env.BUILD_PROJECT }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            r.zip
